[application]
name = "codescope-desktop"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "CodeScope"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
index_on_404 = true
